name = "nerd-cms"
main = "src/worker.js"
compatibility_date = "2024-01-01"
workers_dev = true
preview_urls = true

[build]
command = "./build.sh"

# KV Namespace for content storage
[[kv_namespaces]]
binding = "CONTENT"
id = "77db10ac0b1e4471b51fef221a0523a1"

# Custom Domain Deployment
[[routes]]
pattern = "research.moecapital.com"
custom_domain = true
